[2024-05-14T06:14:53.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T06:14:53.546+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_crawler_list manual__2024-05-14T06:14:51.589257+00:00 [queued]>
[2024-05-14T06:14:53.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_jobs104.data_crawler_list manual__2024-05-14T06:14:51.589257+00:00 [queued]>
[2024-05-14T06:14:53.549+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-14T06:14:53.554+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_crawler_list> on 2024-05-14 06:14:51.589257+00:00
[2024-05-14T06:14:53.557+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T06:14:53.558+0000] {standard_task_runner.py:63} INFO - Started process 112 to run task
[2024-05-14T06:14:53.558+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_jobs104', 'data_crawler_list', 'manual__2024-05-14T06:14:51.589257+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_jobs104.py', '--cfg-path', '/tmp/tmplncac3i2']
[2024-05-14T06:14:53.559+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask data_crawler_list
[2024-05-14T06:14:53.578+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_jobs104.data_crawler_list manual__2024-05-14T06:14:51.589257+00:00 [running]> on host 2c2b6f80804c
[2024-05-14T06:14:53.614+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_jobs104' AIRFLOW_CTX_TASK_ID='data_crawler_list' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T06:14:51.589257+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T06:14:51.589257+00:00'
[2024-05-14T06:14:53.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T06:14:53.630+0000] {logging_mixin.py:188} INFO - test
[2024-05-14T06:14:53.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T06:14:53.631+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_pipeline_jobs104.py", line 33, in data_crawler_list
    filter_params = get_filter_params(role, keyword, isnew, jobexp, mode, order, asc)
                    ^^^^^^^^^^^^^^^^^
NameError: name 'get_filter_params' is not defined
[2024-05-14T06:14:53.639+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline_jobs104, task_id=data_crawler_list, run_id=manual__2024-05-14T06:14:51.589257+00:00, execution_date=20240514T061451, start_date=20240514T061453, end_date=20240514T061453
[2024-05-14T06:14:53.645+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task data_crawler_list (name 'get_filter_params' is not defined; 112)
[2024-05-14T06:14:53.657+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-14T06:14:53.667+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T06:14:53.669+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
